package me.lojosho.hibiscuscommons.packets;

public enum PacketType {
    ENTITY_MOVE,
    ENTITY_LOOK_AT,
    ENTITY_ROTATE,
    ENTITY_ROTATE_HEAD,
    ENTITY_MOUNT,
    ENTITY_LEASH,
    ENTITY_TELEPORT,
    ENTITY_CAMERA,
    ENTITY_SPAWN,
    ENTITY_METADATA,
    ARMOR_STAND_HEAD_POSE,
    ENTITY_DESTROY,
    ENTITY_ATTRIBUTE_UPDATE,
    ENTITY_EQUIPMENT_SLOT_UPDATE,
    PLAYER_TOAST_UPDATE,
    PLAYER_SLOT_UPDATE,
    PLAYER_GAMEMODE_CHANGE,
    PLAYER_INFO_ADD,
    PLAYER_INFO_REMOVE,
    PLAYER_SCOREBOARD_HIDE_USERNAME,
}
